#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSoftware
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HotelManagementSoftwareDataBase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblMember(tblMember instance);
    partial void UpdatetblMember(tblMember instance);
    partial void DeletetblMember(tblMember instance);
    partial void InserttblPayment(tblPayment instance);
    partial void UpdatetblPayment(tblPayment instance);
    partial void DeletetblPayment(tblPayment instance);
    partial void InserttblReservation(tblReservation instance);
    partial void UpdatetblReservation(tblReservation instance);
    partial void DeletetblReservation(tblReservation instance);
    partial void InserttblRoom(tblRoom instance);
    partial void UpdatetblRoom(tblRoom instance);
    partial void DeletetblRoom(tblRoom instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HotelManagementSoftware.Properties.Settings.Default.HotelManagementSoftwareDataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblMember> tblMembers
		{
			get
			{
				return this.GetTable<tblMember>();
			}
		}
		
		public System.Data.Linq.Table<tblPayment> tblPayments
		{
			get
			{
				return this.GetTable<tblPayment>();
			}
		}
		
		public System.Data.Linq.Table<tblReservation> tblReservations
		{
			get
			{
				return this.GetTable<tblReservation>();
			}
		}
		
		public System.Data.Linq.Table<tblRoom> tblRooms
		{
			get
			{
				return this.GetTable<tblRoom>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMembers")]
	public partial class tblMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MemberCode;
		
		private System.Nullable<int> _ReservationCode;
		
		private string _FName;
		
		private string _LName;
		
		private string _Popularity;
		
		private string _FatherName;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _Nationality;
		
		private string _NationId;
		
		private string _BirthPlace;
		
		private EntityRef<tblReservation> _tblReservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberCodeChanging(int value);
    partial void OnMemberCodeChanged();
    partial void OnReservationCodeChanging(System.Nullable<int> value);
    partial void OnReservationCodeChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnLNameChanging(string value);
    partial void OnLNameChanged();
    partial void OnPopularityChanging(string value);
    partial void OnPopularityChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnNationIdChanging(string value);
    partial void OnNationIdChanged();
    partial void OnBirthPlaceChanging(string value);
    partial void OnBirthPlaceChanged();
    #endregion
		
		public tblMember()
		{
			this._tblReservation = default(EntityRef<tblReservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MemberCode
		{
			get
			{
				return this._MemberCode;
			}
			set
			{
				if ((this._MemberCode != value))
				{
					this.OnMemberCodeChanging(value);
					this.SendPropertyChanging();
					this._MemberCode = value;
					this.SendPropertyChanged("MemberCode");
					this.OnMemberCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationCode", DbType="Int")]
		public System.Nullable<int> ReservationCode
		{
			get
			{
				return this._ReservationCode;
			}
			set
			{
				if ((this._ReservationCode != value))
				{
					if (this._tblReservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReservationCodeChanging(value);
					this.SendPropertyChanging();
					this._ReservationCode = value;
					this.SendPropertyChanged("ReservationCode");
					this.OnReservationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(50)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(50)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this.OnLNameChanging(value);
					this.SendPropertyChanging();
					this._LName = value;
					this.SendPropertyChanged("LName");
					this.OnLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="NVarChar(50)")]
		public string Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(50)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationId", DbType="NVarChar(50)")]
		public string NationId
		{
			get
			{
				return this._NationId;
			}
			set
			{
				if ((this._NationId != value))
				{
					this.OnNationIdChanging(value);
					this.SendPropertyChanging();
					this._NationId = value;
					this.SendPropertyChanged("NationId");
					this.OnNationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthPlace", DbType="NVarChar(50)")]
		public string BirthPlace
		{
			get
			{
				return this._BirthPlace;
			}
			set
			{
				if ((this._BirthPlace != value))
				{
					this.OnBirthPlaceChanging(value);
					this.SendPropertyChanging();
					this._BirthPlace = value;
					this.SendPropertyChanged("BirthPlace");
					this.OnBirthPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblReservation_tblMember", Storage="_tblReservation", ThisKey="ReservationCode", OtherKey="ReservationCode", IsForeignKey=true)]
		public tblReservation tblReservation
		{
			get
			{
				return this._tblReservation.Entity;
			}
			set
			{
				tblReservation previousValue = this._tblReservation.Entity;
				if (((previousValue != value) 
							|| (this._tblReservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblReservation.Entity = null;
						previousValue.tblMembers.Remove(this);
					}
					this._tblReservation.Entity = value;
					if ((value != null))
					{
						value.tblMembers.Add(this);
						this._ReservationCode = value.ReservationCode;
					}
					else
					{
						this._ReservationCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblReservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPayment")]
	public partial class tblPayment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaymentCode;
		
		private System.Nullable<int> _ReservationCode;
		
		private System.Nullable<System.DateTime> _PDate;
		
		private System.Nullable<decimal> _PAmount;
		
		private EntityRef<tblReservation> _tblReservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentCodeChanging(int value);
    partial void OnPaymentCodeChanged();
    partial void OnReservationCodeChanging(System.Nullable<int> value);
    partial void OnReservationCodeChanged();
    partial void OnPDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPDateChanged();
    partial void OnPAmountChanging(System.Nullable<decimal> value);
    partial void OnPAmountChanged();
    #endregion
		
		public tblPayment()
		{
			this._tblReservation = default(EntityRef<tblReservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaymentCode
		{
			get
			{
				return this._PaymentCode;
			}
			set
			{
				if ((this._PaymentCode != value))
				{
					this.OnPaymentCodeChanging(value);
					this.SendPropertyChanging();
					this._PaymentCode = value;
					this.SendPropertyChanged("PaymentCode");
					this.OnPaymentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationCode", DbType="Int")]
		public System.Nullable<int> ReservationCode
		{
			get
			{
				return this._ReservationCode;
			}
			set
			{
				if ((this._ReservationCode != value))
				{
					if (this._tblReservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReservationCodeChanging(value);
					this.SendPropertyChanging();
					this._ReservationCode = value;
					this.SendPropertyChanged("ReservationCode");
					this.OnReservationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDate", DbType="Date")]
		public System.Nullable<System.DateTime> PDate
		{
			get
			{
				return this._PDate;
			}
			set
			{
				if ((this._PDate != value))
				{
					this.OnPDateChanging(value);
					this.SendPropertyChanging();
					this._PDate = value;
					this.SendPropertyChanged("PDate");
					this.OnPDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAmount", DbType="Money")]
		public System.Nullable<decimal> PAmount
		{
			get
			{
				return this._PAmount;
			}
			set
			{
				if ((this._PAmount != value))
				{
					this.OnPAmountChanging(value);
					this.SendPropertyChanging();
					this._PAmount = value;
					this.SendPropertyChanged("PAmount");
					this.OnPAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblReservation_tblPayment", Storage="_tblReservation", ThisKey="ReservationCode", OtherKey="ReservationCode", IsForeignKey=true)]
		public tblReservation tblReservation
		{
			get
			{
				return this._tblReservation.Entity;
			}
			set
			{
				tblReservation previousValue = this._tblReservation.Entity;
				if (((previousValue != value) 
							|| (this._tblReservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblReservation.Entity = null;
						previousValue.tblPayments.Remove(this);
					}
					this._tblReservation.Entity = value;
					if ((value != null))
					{
						value.tblPayments.Add(this);
						this._ReservationCode = value.ReservationCode;
					}
					else
					{
						this._ReservationCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblReservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblReservation")]
	public partial class tblReservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReservationCode;
		
		private string _FName;
		
		private string _LName;
		
		private string _Popularity;
		
		private System.Nullable<System.DateTime> _RDate;
		
		private string _Telephone;
		
		private string _Address;
		
		private System.Nullable<int> _RoomCode;
		
		private System.Nullable<int> _NumsOfDays;
		
		private System.Nullable<decimal> _Cost;
		
		private EntitySet<tblMember> _tblMembers;
		
		private EntitySet<tblPayment> _tblPayments;
		
		private EntityRef<tblRoom> _tblRoom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReservationCodeChanging(int value);
    partial void OnReservationCodeChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnLNameChanging(string value);
    partial void OnLNameChanged();
    partial void OnPopularityChanging(string value);
    partial void OnPopularityChanged();
    partial void OnRDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRDateChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnRoomCodeChanging(System.Nullable<int> value);
    partial void OnRoomCodeChanged();
    partial void OnNumsOfDaysChanging(System.Nullable<int> value);
    partial void OnNumsOfDaysChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    #endregion
		
		public tblReservation()
		{
			this._tblMembers = new EntitySet<tblMember>(new Action<tblMember>(this.attach_tblMembers), new Action<tblMember>(this.detach_tblMembers));
			this._tblPayments = new EntitySet<tblPayment>(new Action<tblPayment>(this.attach_tblPayments), new Action<tblPayment>(this.detach_tblPayments));
			this._tblRoom = default(EntityRef<tblRoom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReservationCode
		{
			get
			{
				return this._ReservationCode;
			}
			set
			{
				if ((this._ReservationCode != value))
				{
					this.OnReservationCodeChanging(value);
					this.SendPropertyChanging();
					this._ReservationCode = value;
					this.SendPropertyChanged("ReservationCode");
					this.OnReservationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(50)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(50)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this.OnLNameChanging(value);
					this.SendPropertyChanging();
					this._LName = value;
					this.SendPropertyChanged("LName");
					this.OnLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Popularity", DbType="NVarChar(50)")]
		public string Popularity
		{
			get
			{
				return this._Popularity;
			}
			set
			{
				if ((this._Popularity != value))
				{
					this.OnPopularityChanging(value);
					this.SendPropertyChanging();
					this._Popularity = value;
					this.SendPropertyChanged("Popularity");
					this.OnPopularityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDate", DbType="Date")]
		public System.Nullable<System.DateTime> RDate
		{
			get
			{
				return this._RDate;
			}
			set
			{
				if ((this._RDate != value))
				{
					this.OnRDateChanging(value);
					this.SendPropertyChanging();
					this._RDate = value;
					this.SendPropertyChanged("RDate");
					this.OnRDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomCode", DbType="Int")]
		public System.Nullable<int> RoomCode
		{
			get
			{
				return this._RoomCode;
			}
			set
			{
				if ((this._RoomCode != value))
				{
					if (this._tblRoom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoomCodeChanging(value);
					this.SendPropertyChanging();
					this._RoomCode = value;
					this.SendPropertyChanged("RoomCode");
					this.OnRoomCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumsOfDays", DbType="Int")]
		public System.Nullable<int> NumsOfDays
		{
			get
			{
				return this._NumsOfDays;
			}
			set
			{
				if ((this._NumsOfDays != value))
				{
					this.OnNumsOfDaysChanging(value);
					this.SendPropertyChanging();
					this._NumsOfDays = value;
					this.SendPropertyChanged("NumsOfDays");
					this.OnNumsOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
		public System.Nullable<decimal> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblReservation_tblMember", Storage="_tblMembers", ThisKey="ReservationCode", OtherKey="ReservationCode")]
		public EntitySet<tblMember> tblMembers
		{
			get
			{
				return this._tblMembers;
			}
			set
			{
				this._tblMembers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblReservation_tblPayment", Storage="_tblPayments", ThisKey="ReservationCode", OtherKey="ReservationCode")]
		public EntitySet<tblPayment> tblPayments
		{
			get
			{
				return this._tblPayments;
			}
			set
			{
				this._tblPayments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRoom_tblReservation", Storage="_tblRoom", ThisKey="RoomCode", OtherKey="RoomCode", IsForeignKey=true)]
		public tblRoom tblRoom
		{
			get
			{
				return this._tblRoom.Entity;
			}
			set
			{
				tblRoom previousValue = this._tblRoom.Entity;
				if (((previousValue != value) 
							|| (this._tblRoom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblRoom.Entity = null;
						previousValue.tblReservations.Remove(this);
					}
					this._tblRoom.Entity = value;
					if ((value != null))
					{
						value.tblReservations.Add(this);
						this._RoomCode = value.RoomCode;
					}
					else
					{
						this._RoomCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblRoom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblMembers(tblMember entity)
		{
			this.SendPropertyChanging();
			entity.tblReservation = this;
		}
		
		private void detach_tblMembers(tblMember entity)
		{
			this.SendPropertyChanging();
			entity.tblReservation = null;
		}
		
		private void attach_tblPayments(tblPayment entity)
		{
			this.SendPropertyChanging();
			entity.tblReservation = this;
		}
		
		private void detach_tblPayments(tblPayment entity)
		{
			this.SendPropertyChanging();
			entity.tblReservation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRoom")]
	public partial class tblRoom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoomCode;
		
		private System.Nullable<int> _NumsOfBed;
		
		private System.Nullable<decimal> _RPrice;
		
		private System.Nullable<short> _Status;
		
		private EntitySet<tblReservation> _tblReservations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomCodeChanging(int value);
    partial void OnRoomCodeChanged();
    partial void OnNumsOfBedChanging(System.Nullable<int> value);
    partial void OnNumsOfBedChanged();
    partial void OnRPriceChanging(System.Nullable<decimal> value);
    partial void OnRPriceChanged();
    partial void OnStatusChanging(System.Nullable<short> value);
    partial void OnStatusChanged();
    #endregion
		
		public tblRoom()
		{
			this._tblReservations = new EntitySet<tblReservation>(new Action<tblReservation>(this.attach_tblReservations), new Action<tblReservation>(this.detach_tblReservations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoomCode
		{
			get
			{
				return this._RoomCode;
			}
			set
			{
				if ((this._RoomCode != value))
				{
					this.OnRoomCodeChanging(value);
					this.SendPropertyChanging();
					this._RoomCode = value;
					this.SendPropertyChanged("RoomCode");
					this.OnRoomCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumsOfBed", DbType="Int")]
		public System.Nullable<int> NumsOfBed
		{
			get
			{
				return this._NumsOfBed;
			}
			set
			{
				if ((this._NumsOfBed != value))
				{
					this.OnNumsOfBedChanging(value);
					this.SendPropertyChanging();
					this._NumsOfBed = value;
					this.SendPropertyChanged("NumsOfBed");
					this.OnNumsOfBedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPrice", DbType="Money")]
		public System.Nullable<decimal> RPrice
		{
			get
			{
				return this._RPrice;
			}
			set
			{
				if ((this._RPrice != value))
				{
					this.OnRPriceChanging(value);
					this.SendPropertyChanging();
					this._RPrice = value;
					this.SendPropertyChanged("RPrice");
					this.OnRPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt")]
		public System.Nullable<short> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRoom_tblReservation", Storage="_tblReservations", ThisKey="RoomCode", OtherKey="RoomCode")]
		public EntitySet<tblReservation> tblReservations
		{
			get
			{
				return this._tblReservations;
			}
			set
			{
				this._tblReservations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblReservations(tblReservation entity)
		{
			this.SendPropertyChanging();
			entity.tblRoom = this;
		}
		
		private void detach_tblReservations(tblReservation entity)
		{
			this.SendPropertyChanging();
			entity.tblRoom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserCode;
		
		private string _UserName;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserCodeChanging(int value);
    partial void OnUserCodeChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public tblUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
